FROM node:20.19.0

WORKDIR /app

# Copy dependency files and install
COPY package.json package-lock.json* ./
RUN npm install

# Copy the rest of the source code
COPY . .

# Comands for dev environment (Vite server)
CMD ["npm", "run", "dev"]