version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development  # Esto activa modo debug y recarga automática
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Evita conflictos entre host y contenedor
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend